import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "@/components/ui/toaster";

const fontSans = Poppins({
  weight: ["100", "300", "400", "500", "600"],
  subsets: ["latin", "latin-ext"],
  style: ["normal", "italic"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} antialiased min-h-screen px-4 flex flex-col`}
      >
        <Navbar />
        <main className="flex-grow flex justify-center items-center">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
